/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ArchivoDownload {
    'ardata': any;
    'arfilename': string;
    'armimetype': string;
    'artitle': string;
  }
  interface ArchivoUpload {
    'araccept': string;
    'armaultiple': boolean;
    'artitle': string;
    'getFileData': () => Promise<any>;
  }
}

declare global {


  interface HTMLArchivoDownloadElement extends Components.ArchivoDownload, HTMLStencilElement {}
  var HTMLArchivoDownloadElement: {
    prototype: HTMLArchivoDownloadElement;
    new (): HTMLArchivoDownloadElement;
  };

  interface HTMLArchivoUploadElement extends Components.ArchivoUpload, HTMLStencilElement {}
  var HTMLArchivoUploadElement: {
    prototype: HTMLArchivoUploadElement;
    new (): HTMLArchivoUploadElement;
  };
  interface HTMLElementTagNameMap {
    'archivo-download': HTMLArchivoDownloadElement;
    'archivo-upload': HTMLArchivoUploadElement;
  }
}

declare namespace LocalJSX {
  interface ArchivoDownload {
    'ardata'?: any;
    'arfilename'?: string;
    'armimetype'?: string;
    'artitle'?: string;
  }
  interface ArchivoUpload {
    'araccept'?: string;
    'armaultiple'?: boolean;
    'artitle'?: string;
  }

  interface IntrinsicElements {
    'archivo-download': ArchivoDownload;
    'archivo-upload': ArchivoUpload;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'archivo-download': LocalJSX.ArchivoDownload & JSXBase.HTMLAttributes<HTMLArchivoDownloadElement>;
      'archivo-upload': LocalJSX.ArchivoUpload & JSXBase.HTMLAttributes<HTMLArchivoUploadElement>;
    }
  }
}


